name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    # - run: npm test
    - run: npm run build
    - uses: ncipollo/release-action@v1
      with:
        # TODO Idk if this works, might need to list all files individually
        artifacts: "build/*"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}

# Create a tag (don't include v in semver or obsidian won't play nice)
# $ git tag -a <semver> -m "<release message>"

# Push to trigger the release
# $ git push --tags